### ISSUE TITLE
[Feature] Case insensitive search

### ISSUE THREAD

**Issue by jamesst20** [Okipa/laravel-table#1]
Hi,

Would it be possible to make the search case insensitive ?

Thank you

**Comment by Okipa** [comment]
Hi @jamesst20  
I am wondering if applying case sensitive search queries wouldn't be penalizing for some use cases.  
Could you explain me your use case in order to check how to implement this optionally ?

**Comment by jamesst20** [comment]
There could be many use cases, such as typing a word, a name, a project name.

It's a little annoying to have to respect the word cases especially when they are not all the same

**Comment by jamesst20** [comment]
By the way, i'm talking about case insensitive. It is already case sensitive

**Comment by Okipa** [comment]
@jamesst20  
Sorry, I read too fast. According to my usages, it is already insensitive.  
Could you fork the package and write a test to point the problem ?

**Comment by Okipa** [comment]
@jamesst20  
I just added a test for this : https://github.com/Okipa/laravel-table/blob/689442a45e2c8cfa9b9cd223363ab6837c964b04/tests/Unit/SearchTest.php#L377  
Everything goes fine.

I think your case sensitive could be related to your database version and configuration. Could you tell me which version do you use and which encoding ?

**Comment by jamesst20** [comment]
@Okipa

Sorry for the slow response, here is what I found according to PostgresSQL documentation. (I am using Postgres, I should have mentioned it in the first place).

```
The key word ILIKE can be used instead of LIKE to make the match case-insensitive according to the active locale. This is not in the SQL standard but is a PostgreSQL extension. The operator ~~ is equivalent to LIKE , and ~~* corresponds to ILIKE .
```

**Comment by Okipa** [comment]
Thanks for your return, this should be fixed in https://github.com/Okipa/laravel-table/releases/tag/1.0.9.  
Please reopen if you have an issue.
