### ISSUE TITLE
Issue when using an inner join

### ISSUE THREAD

**Issue by lacrc** [Okipa/laravel-table#13]
Hi! Just wanted to that this package is awesome and the idea behind it is just brilliant!

That being said, I'm having an issue when trying to join my "transactions" and "users" table to generate a Transactions table with user information.

- Users table has column `user.id`
- Transactions table has column `transactions.user_id`

I'm trying to join them in the controller like:
```
$transactions = (new Table)->model(Transaction::class)
            ->query(function ($query) {
                $query->whereNull('deleted_at');
                $query->join('users', 'users.id', '=', 'transactions.id');
            });
```

But I keep getting the error:
```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous (SQL: select * from `transactions` inner join `users` on `users`.`id` = `transactions`.`id` where `transactions`.`deleted_at` is null order by `id` asc limit 25 offset 0)
```

Even without any parameters the `order by id` clause is being added in the query, and it's causing the issue I suppose. 

How can I fix this?

I tried using an alias for the expense.id but then the Table thinks the user.id is the id for the model and it messes up all the route URLs.Can I use an alias for the users.id without using a subquery? (I'm not very good at SQL heh)

I was trying to make the `users.name` field searchable. Using your package, is it possible to use Eloquent to achieve this? (Include the relation and then filter the collection of the table by the given name filter?)

Thanks in advance! :)

**Comment by Okipa** [comment]
Hi there, it seems that you simply forgot to call some `select` or `addSelect` methods in your query.  
You should this part of the doc : https://github.com/Okipa/laravel-table#-searchable.  
You could try :
```php
$table = (new Table)->model(Transaction::class)->query(function($query) {
    $query->select('transactions.*');
    $query->addSelect('users.name as user_name');
    $query->join('users', 'users.id', '=', 'transactions.id');
});
$table->column('user_name')->searchable('users', ['name']);
```

**Comment by lacrc** [comment]
Thank you sir! That worked flawlessly! :)
(i just changed the join to: `'users.id', '=', 'transactions.user_id'`)

**Comment by Okipa** [comment]
Glad you managed to make it work.  
I close the issue as it seems that there is no malfunction in the package.

**Comment by robman2100** [comment]
Is there a way to use eloquent relationships instead of using a straight query?

**Comment by Okipa** [comment]
@robman2100, you can't display a relationship attribute value without using the Table `query` method or the Column `value`/`html` methods.

See e.g. below with the Column `value` method:

```php
$table->column()
    ->title(__('Categories'))
    ->value(fn(NewsArticle $article) => $article->categories->implode('name', ' / '));
```

Or you can use the Table `query` method to prepare an custom attribute that will be displayed:

```php
$table = (new Table)->model(Transaction::class)
    // other methods ...
    ->query(function (Builder $query) {
         $query->select('news_articles.*');
             ->addSelect('news_categories.name as category_name')
             ->join('news_categories', 'news_categories.id', '=', 'news_articles.category_id');
    });
$table->column('category_name');
```
