### ISSUE TITLE
 locale pt-BR don't work

### ISSUE THREAD

**Issue by willewerton** [Okipa/laravel-table#20]
I copied the file laravel-table.php to the locale pt-BR/ but it only appears in English, it does not translate the texts.

**Comment by Okipa** [comment]
Hi @willewerton, are you sure that you're current language is defined as `pt-BR` ?  
If you make a `dd(config('app.locale'))` in your controller, what is the value ?

**Comment by Okipa** [comment]
Hi @willewerton, would you please give me more informations about your problem ?  
Otherwise, I'll consider you managed to get over it and I'll close this issue.  
Thanks !
