### ISSUE TITLE
sortable and searchable problem

### ISSUE THREAD

**Issue by mehdi7e** [Okipa/laravel-table#23]
Hi @Okipa 
I trace in laravel-table code, after 1 hour,  i found a small problem:

If you use Optional Parameters in laravel route, sortable and searchable don't work.
Example Optional Parameters route:
`Route::name('products.index')->get('products/{id?}', 'ProductController@index')`

Pay attention to {id?}

**Comment by Okipa** [comment]
Hey @mehdi7e, thanks for the feedback.  
I investigate ASAP.

**Comment by Okipa** [comment]
Hi @mehdi7e, I tried with an index route with an optional param and everything is going well to me.  
Could please add a test in the `tests/Unit/RoutesTest.php` file that shows the bug ?

**Comment by Okipa** [comment]
I close this issue as I couldn't reproduce the issue.  
I'll reopen it if the bug is reproduced in a test (see comment above).
