### ISSUE TITLE
Hard-coded "fa fa-info-circle" icon in tbody.blade.php

### ISSUE THREAD

**Issue by chris5560** [Okipa/laravel-table#34]
Hi,
inside tbody.blade.php on line 6 there is still a hard-coded "fa fa-info-circle" icon.
Regards
Christian

**Comment by Okipa** [comment]
Hi @chris5560, thanks for reporting this. This has been fixed and released in https://github.com/Okipa/laravel-table/releases/tag/1.2.6.
