### ISSUE TITLE
How to use identifier()

### ISSUE THREAD

**Issue by chris5560** [Okipa/laravel-table#38]
Hi,
I'm very sorry,
it's well described how to set an identifier for a table and when to use it
but it's missing how to implement multiple tables with their identifier inside one view.
Thanks for your support.
Christian

**Comment by Okipa** [comment]
Hi @chris5560, you have to declare as much as tables as you want and send them to the view.

You would have to do this in your controller for example:

```php
public function index()
{
    $usersTable = (new \Okipa\LaravelTable\Table)
    ->model(\App\User::class)->routes(['index' => ['name' => 'users.index']])
    ->identifier('Users table');
    $usersTable->column('name')->sortable()->searchable();

    $newsTable = (new \Okipa\LaravelTable\Table)
    ->model(\App\News::class)->routes(['index' => ['name' => 'news.index']])
    ->identifier('News table');
    $newsTable->column('title')->sortable()->searchable();

    return view('your.view.path', compact('usersTable', 'newsTable'));
}
```

And then in your view:

```blade
    {{ $usersTable }}

    {{ $newsTable }}
```

This way, your will be able to realize actions like searching or sorting independently for each table.
