### ISSUE TITLE
syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

### ISSUE THREAD

**Issue by sannevanleeuwen** [Okipa/laravel-table#49]
I got an issue:
syntax error, unexpected 'bool' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

::Composer\Autoload\includeFile
vendor/okipa/laravel-table/src/Table.php:41

protected bool $configured = false;

**Comment by Okipa** [comment]
Hi @sannevanleeuwen,

I have no info regarding the environnement, the context or anything that could help me to find what could cause the error.

Could you fork the projet and write a test that put the error in evidence ?

Or at least give more data ? Right know I can't do anything

**Comment by sannevanleeuwen** [comment]
I found the problem, it was the php version. I updated it from 7.2 to 7.4
