### ISSUE TITLE
Table cell content not escaped unless it's a custom value

### ISSUE THREAD

**Issue by PaulMcRoar** [Okipa/laravel-table#54]
Hi,

The content of table cells isn't being escaped unless it's a custom value.

I've kept the description short because github has been crashing when trying to report issues on this project.

**Comment by PaulMcRoar** [comment]
(Managed to create an issue this time! :-)

I think this is in tbody.blade.php  , we fall back to , on line 60

@else
   {!! $value !!}
@endif

and I think we should have

@else
  {{ $value }}
@endif

**Comment by Okipa** [comment]
Hi @PaulMcRoar, thanks for reporting this, this has been fixed here : https://github.com/Okipa/laravel-table/pull/56.

I will release this fix in a few minutes.
