### ISSUE TITLE
need to also urldecode the value in extractHiddenFieldsToGenerate

### ISSUE THREAD

**Issue by PaulMcRoar** [Okipa/laravel-table#68]
Traits/Table/HasPagination.php

line 34 needs to be

            $generatedHiddenFields[urldecode(head($argument))] = urldecode(last($argument));

Otherwise if there is a space, say, in the value of the hidden field it will be replaced with +, so (in my use case) the status of 'In Progress' , which I'm using as a filter, is hidden, and when searching on the filtered rows, the hidden field has the value "In+Progress" and the filtering breaks.

**Comment by Okipa** [comment]
This has also been fixed in https://github.com/Okipa/laravel-table/pull/69.

Thanks 👍
