### ISSUE TITLE
Custom Actions

### ISSUE THREAD

**Issue by JeffreyDavidson** [Okipa/laravel-table#70]
I'm trying to understand how to create a custom button that will send a patch request action to a specific route. Is this possible with this package?

**Comment by Okipa** [comment]
Hi @JeffreyDavidson, I'm afraid you can't do this right now.

I never had to implement this because I always add custom actions (buttons, links, ...) in table cells with `->html()` column rendering.

I would accept a tested PR for an implementation that would allow to add a custom actions.
