### ISSUE TITLE
Suggestion: Allow diffForHumans for dateTimeFormat

### ISSUE THREAD

**Issue by tomcrofty** [Okipa/laravel-table#72]
diffForHumans() is a function of a Carbon DateTime object, with the current dateTimeFormat() function we can only use traditional PHP date formatting methods. This implementation would be really fantastic.

Loving this package, thanks a bunch :D

**Comment by tomcrofty** [comment]
For anyone wondering, the current best implementation is to edit the value of the column, like below:
```php
$table->column('next_bill')->value(function(User $user) {
    return $user->next_bill->diffForHumans();
})->sortable()->title('Next Bill');
```

**Comment by Okipa** [comment]
Hi @tomcrofty, thanks for the proposal, I would accept a tested for this addition 👍🏻

**Comment by Okipa** [comment]
Closing this as creating formatters is a feature that will be available in V5.
