### ISSUE TITLE
Searchable by integer column

### ISSUE THREAD

**Issue by dirtyfrank23** [Okipa/laravel-table#74]
Hello, i've been experimenting with your tables for a bit and it's great but I just noticed that I cannot search by an integer field. I see that you use lower() and cast the searchable columns to text. Could you possibly add the feature to search by a numeric or integer field ?

**Comment by Okipa** [comment]
Hi @dirtyfrank23, sorry for the delayed answer.

Would you mind to precise your use case ? The search feature provides a case insensitive and partial search on text but there is ways to achieve alternative filtering if you need to.

**Comment by dirtyfrank23** [comment]
Hi Okipa, thanks for replying. I have the table below and I'm trying to filter by column 'Number' (integer in DB) and am receiving the following error in Laravel. 

![invoice_table_query](https://user-images.githubusercontent.com/80624397/124230023-28ca2800-db17-11eb-88e0-6e59f5d73658.PNG)

![invoice_table_columns](https://user-images.githubusercontent.com/80624397/124230033-2bc51880-db17-11eb-8601-28455c6d4017.PNG)


![invoices_table](https://user-images.githubusercontent.com/80624397/124229784-cffa8f80-db16-11eb-805c-c0dcce617fd0.PNG)

![invoices_table_error](https://user-images.githubusercontent.com/80624397/124229914-00dac480-db17-11eb-8ee3-5e3c8480cd2e.PNG)

**Comment by Okipa** [comment]
@dirtyfrank23 I couldn't reproduce your issue with a simple test case. In fact it is working with a basic integer field.

I believe this is an issue related to your specific sql query. In your error message it is recommended to cast your invoice_number in a string, did you try that ? I think this could actually work.

The lowercase is needed on the package size to provide a partial and insensitive case search behavior and it cannot be touched without including some breaking changes.

**Comment by Okipa** [comment]
I've created a PR to add this case verification : https://github.com/Okipa/laravel-table/pull/75/files
