### ISSUE TITLE
[Feature Request] Feature to reorder rows

### ISSUE THREAD

**Issue by adityaa-codes** [Okipa/laravel-table#80]
Draggable Components to reorder their sequence of the rows and update them accordingly

**Comment by Okipa** [comment]
Hi @adityaa-codes, I'm currently working on the v5 of this package, that will based on Livewire and will provide the additional following features:
* multiple rows selection and ability to create custom actions for selected rows
* ability to generate table from collection
* allowing all current and new actions without having to reload the page
* keeping the way we configure tables as close as it is currently working, as I think this is quite appreciated
* allowing to switch UI (Bootstrap5, Bootstrap4, TailwindCSS)
* Reordering table with drag and drop

This work will take several months to finish but you should know that the feature you are requesting will normally be part of this future version.

**Comment by adityaa-codes** [comment]
That's Awesome, Thank you so much, Waiting for the update
