### ISSUE TITLE
Error when using multiple aliases with join statements

### ISSUE THREAD

**Issue by denisgoryaynov** [Okipa/laravel-table#83]
When using multiple aliases with join statements inside the `query()` function of the Table class I get an error saying that `The table column with related « code » database column is searchable and does not exist in the « products » (aliased as « users ») table.` while in fact the products table is not aliased to anything. My query looks like this:
```
$builder
  ->join(
    'products',
    'products.id',
    'allocations.product_id',
  )
  ->join('sites', 'sites.id', 'allocations.site_id')
  ->join('users as agents', 'agents.id', 'allocations.agent_id')
  ->join('users as managers', 'managers.id', 'agents.parent_id')
```

Removing `sortable` and `searchable` from the products column works but it's not the desired result.

**Comment by Okipa** [comment]
Hi @denisgoryaynov, you should look here to get what you want : https://github.com/Okipa/laravel-table#column-searchable

I don't see any `select` on your query, and I can't help you right now if I can't see how you tried to configure your columns.

Try to reproduce the example given in the configuration and in case of troubles, please give your entire configuration so I can help you.

**Comment by Okipa** [comment]
Closing this issue as there is no feedback, I assume the problem has been fixed.
